---
name: Deploy Sanity
on:
  push:
    branches:
      - main
jobs:
  backup-dataset:
    runs-on: ubuntu-18.04
    name: Backup dataset
    steps:
      - uses: actions/checkout@v2
      - run: npm install --global sanity@latest && npx sanity dataset export production backup.tar.gz
        working-directory: backup
        env:
          SANITY_STUDIO_API_PROJECT_ID: u0v1th4q
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: backup
          path: backup/backup.tar.gz
          retention-days: 10
