---
name: Backup
on:
    push:
        branches:
            - main
jobs:
    backup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run backup script
              run: npm i --legacry-peer-deps && node index.js --token=${{ secrets.SANITY_AUTH_TOKEN }} --projectId=${{ secrets.SANITY_PROJECT_ID }}
